import os
import re
import jsonlines

# This program is used to convert a MD file to a JSONL file. And it is mainly generated by ChatGPT;)
print("Current working directory:", os.getcwd())

# I suppose that the pwd is the root of the project
file_path = r"prompts\\fine_tuning.md"
ignore_path = r"ignore\\" + file_path
if os.path.exists(ignore_path):
    file_path = ignore_path


def extract_content(md_content):
    results = []
    headings = re.findall(r"\*\*(.*?)\*\*", md_content, flags=re.DOTALL)
    contents = re.split(r"\*\*.*?\*\*", md_content, flags=re.DOTALL)[1:]
    if len(headings) == len(contents):
        for i in range(len(headings)):
            prompt = headings[i].strip()
            completion = contents[i].strip()
            results.append({"prompt": prompt, "completion": completion})
    return results


# Read the MD file
with open(file_path, "r", encoding="utf-8") as file:
    md_content = file.read()

# Process the content
results = extract_content(md_content)

# Print the extracted content
for result in results:
    print(result)


# Export the extracted content to a JSONL file
with jsonlines.open(file_path + ".jsonl", mode="w") as writer:
    for result in results:
        writer.write(result)
